# 基础路径配置
baseDocPath=JavaDoc/docs/api/java.base
suiteBasePath=jdk17u-dev/test/jdk/
testDir=test
jdkTestPath=jdk17u-dev/test
jdkSourcePath=jdk17u-dev/src
defaultSourcePrefix=java.base/share/classes
bugReportDir=BugReport
logFile=result.log

# 依赖jar包配置
jars=Dependency/testng-7.10.2.jar,Dependency/junit-jupiter-api-5.11.4.jar,Dependency/junit-jupiter-engine-5.11.4.jar,Dependency/junit-4.13.1.jar

# 文件处理配置
maxFileSize=10000

# 线程池配置
threadMultiplierGenerate=3
threadMultiplierExecute=2
executorShutdownTimeoutSeconds=30

# 模板配置
templateMode=SpecTest

# 系统配置
useSystemProxies=true